### ISSUE TITLE
Can't show out panel.

### ISSUE THREAD

**Issue by kimsungwhee** [music4kid/FastStub-Xcode#1]
@music4kid 
I pressed command+control+k keys but not show out panel.
What's problem with me.
thanks.

**Comment by music4kid** [comment]
My bad, I was not aware Alcatraz does not support workspace, just fixed it, try remove it and reinstall.  Let me know if it works.

**Comment by kimsungwhee** [comment]
@music4kid 
Great job.
It's work for me.
Thank you.
