### ISSUE TITLE
initWith生成的初始化方法返回值类型和参数类型不对

### ISSUE THREAD

**Issue by lujing666208** [music4kid/FastStub-Xcode#18]
使用initWith选项自动生成的初始化方法返回值是void,不是instanceType,而且参数中属性的类型是基本类型时，也会带*号，如图：

<img width="571" alt="2016-07-07 11 31 05" src="https://cloud.githubusercontent.com/assets/13326247/16641771/5ebbee6c-4436-11e6-8f35-45aa32ce8b86.png">

**Comment by music4kid** [comment]
fixed，thanks。
